// <auto-generated />
using System;
using HRMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HRMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250901101816_SeedSigningKeys")]
    partial class SeedSigningKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HRMS.Models.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<TimeOnly?>("CheckInTime")
                        .HasColumnType("time")
                        .HasColumnName("check_in_time");

                    b.Property<TimeOnly?>("CheckOutTime")
                        .HasColumnType("time")
                        .HasColumnName("check_out_time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("EmployeeId", "Date")
                        .IsUnique();

                    b.ToTable("attendances", (string)null);
                });

            modelBuilder.Entity("HRMS.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("HeadEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("head_employee_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("HeadEmployeeId")
                        .IsUnique()
                        .HasFilter("\"head_employee_id\" IS NOT NULL");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440000"),
                            CreatedAt = new DateTime(2025, 9, 1, 10, 18, 15, 481, DateTimeKind.Utc).AddTicks(5329),
                            Description = "Human Resource dept",
                            IsDeleted = false,
                            Name = "HR",
                            UpdatedAt = new DateTime(2025, 9, 1, 10, 18, 15, 481, DateTimeKind.Utc).AddTicks(5471)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440001"),
                            CreatedAt = new DateTime(2025, 9, 1, 10, 18, 15, 481, DateTimeKind.Utc).AddTicks(5717),
                            Description = "engineering dept",
                            IsDeleted = false,
                            Name = "Engineering",
                            UpdatedAt = new DateTime(2025, 9, 1, 10, 18, 15, 481, DateTimeKind.Utc).AddTicks(5717)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440002"),
                            CreatedAt = new DateTime(2025, 9, 1, 10, 18, 15, 481, DateTimeKind.Utc).AddTicks(5719),
                            Description = "Finance dept",
                            IsDeleted = false,
                            Name = "Finance",
                            UpdatedAt = new DateTime(2025, 9, 1, 10, 18, 15, 481, DateTimeKind.Utc).AddTicks(5720)
                        });
                });

            modelBuilder.Entity("HRMS.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<int>("LeavesUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("leaves_used");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("salary");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int>("TotalLeaves")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(25)
                        .HasColumnName("total_leaves");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ManagerId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PositionId");

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            Address = "HQ",
                            ConcurrencyStamp = "50637a17-e898-41b9-9bf9-03588237e0ac",
                            CreatedAt = new DateTime(2025, 9, 1, 10, 18, 15, 422, DateTimeKind.Utc).AddTicks(9305),
                            DateOfBirth = new DateTime(2003, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("550e8400-e29b-41d4-a716-446655440001"),
                            Email = "ruhma@email.com",
                            EmailConfirmed = true,
                            FirstName = "Ruhma",
                            HireDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Anwar",
                            LeavesUsed = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "RUHMA@EMAIL.COM",
                            NormalizedUserName = "RUHMA@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM6b8Xvl9J4y1JCdyR11wOFFWOeXw4vq4p5Z3HwJMCWRs8tXgWG2oyzyGAobpqwfVg==",
                            PhoneNumber = "03077147775",
                            PhoneNumberConfirmed = true,
                            PositionId = new Guid("550e8400-e29b-41d4-a716-446655440101"),
                            Salary = 1000m,
                            SecurityStamp = "59a3bb0b-8846-4058-99e7-7b532930f9b0",
                            TotalLeaves = 25,
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 9, 1, 10, 18, 15, 422, DateTimeKind.Utc).AddTicks(9440),
                            UserName = "ruhma@email.com"
                        });
                });

            modelBuilder.Entity("HRMS.Models.Leave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Casual")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EndDate");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("StartDate");

                    b.HasIndex("Status");

                    b.ToTable("leaves", (string)null);
                });

            modelBuilder.Entity("HRMS.Models.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("SalaryRangeMax")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("salary_range_max");

                    b.Property<decimal>("SalaryRangeMin")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("salary_range_min");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("positions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440100"),
                            CreatedAt = new DateTime(2025, 9, 1, 10, 18, 15, 477, DateTimeKind.Utc).AddTicks(6450),
                            DepartmentId = new Guid("550e8400-e29b-41d4-a716-446655440000"),
                            Description = "human resource manager",
                            IsDeleted = false,
                            SalaryRangeMax = 200000.00m,
                            SalaryRangeMin = 320000.00m,
                            Title = "HR Manager",
                            UpdatedAt = new DateTime(2025, 9, 1, 10, 18, 15, 477, DateTimeKind.Utc).AddTicks(6602)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440101"),
                            CreatedAt = new DateTime(2025, 9, 1, 10, 18, 15, 477, DateTimeKind.Utc).AddTicks(6867),
                            DepartmentId = new Guid("550e8400-e29b-41d4-a716-446655440001"),
                            Description = "snr soft engr",
                            IsDeleted = false,
                            SalaryRangeMax = 200000.00m,
                            SalaryRangeMin = 150000.00m,
                            Title = "Software Engineer",
                            UpdatedAt = new DateTime(2025, 9, 1, 10, 18, 15, 477, DateTimeKind.Utc).AddTicks(6868)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440102"),
                            CreatedAt = new DateTime(2025, 9, 1, 10, 18, 15, 477, DateTimeKind.Utc).AddTicks(6872),
                            DepartmentId = new Guid("550e8400-e29b-41d4-a716-446655440002"),
                            Description = "snr soft engr",
                            IsDeleted = false,
                            SalaryRangeMax = 200000.00m,
                            SalaryRangeMin = 320000.00m,
                            Title = "Financial Analyst",
                            UpdatedAt = new DateTime(2025, 9, 1, 10, 18, 15, 477, DateTimeKind.Utc).AddTicks(6872)
                        });
                });

            modelBuilder.Entity("HRMS.Models.SigningKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SigningKeys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("130990e7-b4ca-464b-987c-a75de392cad2"),
                            CreatedAt = new DateTime(2025, 9, 1, 15, 18, 15, 403, DateTimeKind.Utc).AddTicks(6534),
                            ExpiresAt = new DateTime(2026, 9, 1, 10, 18, 15, 403, DateTimeKind.Utc).AddTicks(6758),
                            IsActive = true,
                            KeyId = "e309ce68-e280-4fb2-a88f-d24ee37ddb51",
                            PrivateKey = "MIIEpAIBAAKCAQEAvwtEj2A6U6hsWueTq7wnQ11CcGm8qrgTGUKjHDdJwKyvXjJMWiXnR3DuBKpZndXOyQEvOtIcwRzhMmfFkBuBSE66QKhp9IU0mSpKvRLn5uPqWEPoJIRdadGat5KdjsmQT5oUhH8yvfgxq829hhZaxJfUDcTPuPVFwcnnV6/5qtxjF3DkptZ2wIVhOnUkpIZc3h6IpDaBku+j9cLw1ho7AAYpNLiE2SC8k0/9+4EAU1hGYXPJd7HFht3Cb584EnfO9wOYQy8BhqiCwImGOLhmNkYtPLhnyG79nu2iC9ztm3qqx75elYscmkyMERUe2s9TtEmnZpYFmX4V0pZR3t4X4QIDAQABAoIBABXVcdZ5BvF8tDWHdecQr+QRCoDSdM+GDhi69u1InFM66Sf406UR4+bUTz+VQHy7bNCoI/+y97pSVKJwHbIkkpfy93JgTQu3FZXTsYr+WCaZMbU4vZU+03Y+kFIenYcuHiIa1/F0oBX6AaNC9kAW2fTR7VhNf/gBgCFvs9Lft8cBCl7NsHlmOMkk7Li65pxm9rU9D8e4HrcpOELFO2At2wGDhAdWQEHrFlrvQ8zHLOXXkWztGyvxT2kCNCP9EnF61dcoRwrF11x3lSMO0vJYtwDTZ7Ve2Uv9FrNm/yjEGzKKDGYET7/CHoyO1jOy3HpdgWeG7emMvsk+1zAGtMyjwCkCgYEA7OZJzLaXFpgpl+NB5T5ExXY/K2KJwbHZTBxiwq57bnDG8WaUQvKYL2taCXPMaPSQcuP4QEDNRJD/TZLqdiX6bptL3IQYn8H20xERuBioS/rfpb3CXMJ/Wh1raadzTzKjMx8QkOIsCm0sTRbC6VZ/PIPB9eGafErILQzHr1D6fGsCgYEAznKAMDyUVop2PtwIRerRCVnvdj+yIotM6ZabgodHdzPEMIe5OROahShQxxIYvx6lIBo1d0TSNLsGrhIwVWvL8VhuuG3qoNogTYBwbCDlDyx8CzHnHkV+5KJUrL7OhCNY+THZSX6JCD3CBeF4jT8RJBLrclcpDRoE/AUcMWBGj+MCgYEA0/jnVh6XKKd0qCy33LkP7iP1OAvOuZs6lUjc8dgQJ+0PhhdEWHcbx2pmQQj1gYA79CGaE1woj86yMqZf1uH6qJealLE6G1ECWy/ty+18Qag0D+iwjjGWpHqojvw/SEFGGEsWlp1ZzOaM+lmAhCtaZDp9Blcc1VRQs0a5MlziFQsCgYBy5w+pyU3WjOIbQmPoZjVKOyAodHM0/sskB4suLxT7p3g+eowA1IRgMHwlEFFtriTBpVS0uT011BJ3t+/m20R7Y3jcdXDtbfokqKPpyrUyqNOxd2jnVE63+hGew+Q1b2cJ61DAswiZ6aWfmEp8cumbZlxdG13hyOWVT1LNuIQNeQKBgQDh5HEO2btWD0kQz6ad3wrexflV3p9i/pDsTQvoSpZ1+DwvwMnWC1mrdna/KlQGZg75UsByZ+KD43+v/OVA2M20o68TusIFibnIUvnEaLTUQhJsWgW4DLCTcFTlMH2xo/gCgv8/hYkhPh6J7nvQ9J8H8NU7LkuEOPue8xXD6zgSXA==",
                            PublicKey = "MIIBCgKCAQEAvwtEj2A6U6hsWueTq7wnQ11CcGm8qrgTGUKjHDdJwKyvXjJMWiXnR3DuBKpZndXOyQEvOtIcwRzhMmfFkBuBSE66QKhp9IU0mSpKvRLn5uPqWEPoJIRdadGat5KdjsmQT5oUhH8yvfgxq829hhZaxJfUDcTPuPVFwcnnV6/5qtxjF3DkptZ2wIVhOnUkpIZc3h6IpDaBku+j9cLw1ho7AAYpNLiE2SC8k0/9+4EAU1hGYXPJd7HFht3Cb584EnfO9wOYQy8BhqiCwImGOLhmNkYtPLhnyG79nu2iC9ztm3qqx75elYscmkyMERUe2s9TtEmnZpYFmX4V0pZR3t4X4QIDAQAB"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Hr",
                            NormalizedName = "HR"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("HRMS.Models.Attendance", b =>
                {
                    b.HasOne("HRMS.Models.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRMS.Models.Department", b =>
                {
                    b.HasOne("HRMS.Models.Employee", "HeadEmployee")
                        .WithOne("DepartmentLed")
                        .HasForeignKey("HRMS.Models.Department", "HeadEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HeadEmployee");
                });

            modelBuilder.Entity("HRMS.Models.Employee", b =>
                {
                    b.HasOne("HRMS.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS.Models.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HRMS.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Manager");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("HRMS.Models.Leave", b =>
                {
                    b.HasOne("HRMS.Models.Employee", "Approver")
                        .WithMany("ApprovedLeaves")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HRMS.Models.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRMS.Models.Position", b =>
                {
                    b.HasOne("HRMS.Models.Department", "Department")
                        .WithMany("Positions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HRMS.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HRMS.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HRMS.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMS.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("HRMS.Models.Employee", b =>
                {
                    b.Navigation("ApprovedLeaves");

                    b.Navigation("Attendances");

                    b.Navigation("DepartmentLed");

                    b.Navigation("LeaveRequests");

                    b.Navigation("Subordinates");
                });

            modelBuilder.Entity("HRMS.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
