// <auto-generated />
using System;
using HRMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HRMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HRMS.Models.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<TimeOnly?>("CheckInTime")
                        .HasColumnType("time")
                        .HasColumnName("check_in_time");

                    b.Property<TimeOnly?>("CheckOutTime")
                        .HasColumnType("time")
                        .HasColumnName("check_out_time");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("EmployeeId", "Date")
                        .IsUnique();

                    b.ToTable("attendances", (string)null);
                });

            modelBuilder.Entity("HRMS.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("HeadEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("head_employee_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("HeadEmployeeId")
                        .IsUnique()
                        .HasFilter("\"head_employee_id\" IS NOT NULL");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440000"),
                            CreatedAt = new DateTime(2025, 9, 2, 10, 38, 50, 121, DateTimeKind.Utc).AddTicks(2928),
                            Description = "Human Resource dept",
                            IsDeleted = false,
                            Name = "HR",
                            UpdatedAt = new DateTime(2025, 9, 2, 10, 38, 50, 121, DateTimeKind.Utc).AddTicks(3079)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440001"),
                            CreatedAt = new DateTime(2025, 9, 2, 10, 38, 50, 121, DateTimeKind.Utc).AddTicks(3324),
                            Description = "engineering dept",
                            IsDeleted = false,
                            Name = "Engineering",
                            UpdatedAt = new DateTime(2025, 9, 2, 10, 38, 50, 121, DateTimeKind.Utc).AddTicks(3324)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440002"),
                            CreatedAt = new DateTime(2025, 9, 2, 10, 38, 50, 121, DateTimeKind.Utc).AddTicks(3326),
                            Description = "Finance dept",
                            IsDeleted = false,
                            Name = "Finance",
                            UpdatedAt = new DateTime(2025, 9, 2, 10, 38, 50, 121, DateTimeKind.Utc).AddTicks(3327)
                        });
                });

            modelBuilder.Entity("HRMS.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<int>("LeavesUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("leaves_used");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("salary");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int>("TotalLeaves")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(25)
                        .HasColumnName("total_leaves");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ManagerId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PositionId");

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            Address = "HQ",
                            ConcurrencyStamp = "f1948295-43db-4caa-92b3-2e3a638b2d39",
                            CreatedAt = new DateTime(2025, 9, 2, 10, 38, 50, 54, DateTimeKind.Utc).AddTicks(1641),
                            DateOfBirth = new DateTime(2003, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("550e8400-e29b-41d4-a716-446655440001"),
                            Email = "ruhma@email.com",
                            EmailConfirmed = true,
                            FirstName = "Ruhma",
                            HireDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Anwar",
                            LeavesUsed = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "RUHMA@EMAIL.COM",
                            NormalizedUserName = "RUHMA@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECjOtwAmJ6isqDL6segRL4sF5zfiyfw6EB9tbv8ctixJWOewcWNo9WzANd2mb5bmJg==",
                            PhoneNumber = "03077147775",
                            PhoneNumberConfirmed = true,
                            PositionId = new Guid("550e8400-e29b-41d4-a716-446655440101"),
                            Salary = 1000m,
                            SecurityStamp = "b03e1d0d-2049-4f72-92db-8c8482b590b4",
                            TotalLeaves = 25,
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 9, 2, 10, 38, 50, 54, DateTimeKind.Utc).AddTicks(1783),
                            UserName = "ruhma@email.com"
                        });
                });

            modelBuilder.Entity("HRMS.Models.Leave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Casual")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EndDate");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("StartDate");

                    b.HasIndex("Status");

                    b.ToTable("leaves", (string)null);
                });

            modelBuilder.Entity("HRMS.Models.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("SalaryRangeMax")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("salary_range_max");

                    b.Property<decimal>("SalaryRangeMin")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("salary_range_min");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("positions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440100"),
                            CreatedAt = new DateTime(2025, 9, 2, 10, 38, 50, 117, DateTimeKind.Utc).AddTicks(5289),
                            DepartmentId = new Guid("550e8400-e29b-41d4-a716-446655440000"),
                            Description = "human resource manager",
                            IsDeleted = false,
                            SalaryRangeMax = 200000.00m,
                            SalaryRangeMin = 320000.00m,
                            Title = "HR Manager",
                            UpdatedAt = new DateTime(2025, 9, 2, 10, 38, 50, 117, DateTimeKind.Utc).AddTicks(5489)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440101"),
                            CreatedAt = new DateTime(2025, 9, 2, 10, 38, 50, 117, DateTimeKind.Utc).AddTicks(5757),
                            DepartmentId = new Guid("550e8400-e29b-41d4-a716-446655440001"),
                            Description = "snr soft engr",
                            IsDeleted = false,
                            SalaryRangeMax = 200000.00m,
                            SalaryRangeMin = 150000.00m,
                            Title = "Software Engineer",
                            UpdatedAt = new DateTime(2025, 9, 2, 10, 38, 50, 117, DateTimeKind.Utc).AddTicks(5757)
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440102"),
                            CreatedAt = new DateTime(2025, 9, 2, 10, 38, 50, 117, DateTimeKind.Utc).AddTicks(5760),
                            DepartmentId = new Guid("550e8400-e29b-41d4-a716-446655440002"),
                            Description = "snr soft engr",
                            IsDeleted = false,
                            SalaryRangeMax = 200000.00m,
                            SalaryRangeMin = 320000.00m,
                            Title = "Financial Analyst",
                            UpdatedAt = new DateTime(2025, 9, 2, 10, 38, 50, 117, DateTimeKind.Utc).AddTicks(5761)
                        });
                });

            modelBuilder.Entity("HRMS.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("HRMS.Models.SigningKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("signing_keys", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d15a1571-e276-4f8c-87de-ff3848349c92"),
                            CreatedAt = new DateTime(2025, 9, 2, 15, 38, 50, 38, DateTimeKind.Utc).AddTicks(1721),
                            ExpiresAt = new DateTime(2026, 9, 2, 10, 38, 50, 38, DateTimeKind.Utc).AddTicks(1947),
                            IsActive = true,
                            KeyId = "1c6abb0c-533f-47d0-a78b-4f7357b05532",
                            PrivateKey = "MIIEpAIBAAKCAQEAxgV3trGyIqKf4p0Y0I9UKEBkn7i875IaPxx3lF6PqIYg/3TNz9yAXIYEwQhgOLTj1KFvLKbXIBT3DYuhkckStDGaN+YMnnbWDW0agU0D1H8j5Jgt+GuaPOu1z1vibDmvElKtfbjcYkwGZyz6+WQf9eFEgc0adxlBVAYgIiXcnUTMS1/vwXix5gMdw1zFGWqp1ThGGVsu1v6byrSdtYKiqc1etyyWDuakYR9yhCIArofPm8s27tRLzRswUaj85tPnUQHNuLGU+3Zzypka8arxQp3Ii63A1dEc+iPahe9pvPvPht/O7aKDuODNIDHLMkqrqTltXNTX0c1wj3x/lsVdSQIDAQABAoIBAF/2pl1TIBDI3tLjbvMjgpU/H4SH8ofnNfD/yrOMX/I7jiI+aL8jDNHJ4OPrOzY/82lIEqiA8iAKCO/3iwUrfHT21NXiFpt026cGCKJAwGpqcuqFFUIeY1DCqgkjbkckbUNj7c/Pln3Meg3mLnpNm299C8Ybr4eoJZCip0/lKVTM9wkqLm2lorbMhAVXo1Q/qhmqHsIzo7CPI713P0ze7++l2jZGFVx8PUqWKXevpAWi2NWFFnTecngopp7OV9w9vX6lzAW/foKuRZiOisb6N5CqjdLjUfVf9apYaYh3sGl0LymEcLxJU/7t+mEXGq31p0Yl9XbdjlANACl2T6PriUECgYEAys/0lQxOiIvznwhW3SW3IqweDv2qJl9Y1Ezgei1NiauF84QWDzxbHB/0KVy323p+/+YYBZU2VoTZAedx/x6in9p3eEt23534DmCA1DglqRXxoba2k//TtWe1GaMbRU41nDFb8JvhgZVxxypQ54OikKRiyRyqMbMJUk8rHitzet8CgYEA+fPdbdxWhfqhhxk0Q65K8ubofrby40p8eZ9miu48Fmzi37AvEMv0bssB2sZ8n0rvaso49tj/RO5HWY8PNzdRLz8O03auGY4j7GNa7OtDASegK37OYeZ7chBy+mX6gMOY/hbO2ECFKk9EQpUkHYw4P63v01lrekplEU1rndKIVNcCgYAkAYVnjLbIkSggPMfHHTIFKs9vU+OISncnwbo8lpxka5otYG7WJ535QUcErNxLT9UKM1xiaVorRAyOxPs9EsBGZu+84JDrJE1sp/9XLdypxyaN0jVZ0xpP42iIc6ecx0THRRAQiGwhqFl5xW51m64ZxcVv9PHWPvXRshJymb43uwKBgQDTDuu796EL8u1wMYUjXUomP3q0fPEtodjnrgSdbbtJSFpufcvQSBg3ca44OQBEVbdCmk1tiyBJ6VZQNm+ntUsVNQ7k2sL6Cz8kPWUqxyFGGVqzP5kvq7ozP9aGv5O+JOvMKiAxFJIdft9pxZvAY4Wfp9TpxwjtM2KSMKidlIfP8wKBgQDHh20Ug2Qdh6GDYWW975avc9ZtzybkR3H9+JYeJ+9tUGjrmCmhTxhsr6jB39U+PDmHDJYsKT98UUz0oaZ8R1OAiQpJD2dotSzjPtUOjMbG0vLowiyq4uX8v4W0FtApu9Pj8Y8ZvuwaUygS7XoRtKF/U1hRJq3dRlqiiS3iBV3k0w==",
                            PublicKey = "MIIBCgKCAQEAxgV3trGyIqKf4p0Y0I9UKEBkn7i875IaPxx3lF6PqIYg/3TNz9yAXIYEwQhgOLTj1KFvLKbXIBT3DYuhkckStDGaN+YMnnbWDW0agU0D1H8j5Jgt+GuaPOu1z1vibDmvElKtfbjcYkwGZyz6+WQf9eFEgc0adxlBVAYgIiXcnUTMS1/vwXix5gMdw1zFGWqp1ThGGVsu1v6byrSdtYKiqc1etyyWDuakYR9yhCIArofPm8s27tRLzRswUaj85tPnUQHNuLGU+3Zzypka8arxQp3Ii63A1dEc+iPahe9pvPvPht/O7aKDuODNIDHLMkqrqTltXNTX0c1wj3x/lsVdSQIDAQAB"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("HRMS.Models.Attendance", b =>
                {
                    b.HasOne("HRMS.Models.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRMS.Models.Department", b =>
                {
                    b.HasOne("HRMS.Models.Employee", "HeadEmployee")
                        .WithOne("DepartmentLed")
                        .HasForeignKey("HRMS.Models.Department", "HeadEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HeadEmployee");
                });

            modelBuilder.Entity("HRMS.Models.Employee", b =>
                {
                    b.HasOne("HRMS.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS.Models.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HRMS.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Manager");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("HRMS.Models.Leave", b =>
                {
                    b.HasOne("HRMS.Models.Employee", "Approver")
                        .WithMany("ApprovedLeaves")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HRMS.Models.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRMS.Models.Position", b =>
                {
                    b.HasOne("HRMS.Models.Department", "Department")
                        .WithMany("Positions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HRMS.Models.RefreshToken", b =>
                {
                    b.HasOne("HRMS.Models.Employee", "Employee")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HRMS.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HRMS.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HRMS.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMS.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("HRMS.Models.Employee", b =>
                {
                    b.Navigation("ApprovedLeaves");

                    b.Navigation("Attendances");

                    b.Navigation("DepartmentLed");

                    b.Navigation("LeaveRequests");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Subordinates");
                });

            modelBuilder.Entity("HRMS.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
